export const ausentesExcedentesArray = [
  {
    descricao: "Lista de Ausentes",
    pessoas: [
      "Adeilma Rodrigues da Silva",
      "Alan Kleber Santos de Almeida",
      "Carolayne Nascimento Rocha",
      "Diego Melo Cardoso social Samantha",
      "Diogo Ramos Cerqueira",
      "Gabriel Reis Ferreira",
      "Hevellin Santos Cardoso",
      "Luana Maria Figueiredo Paes",
      "Maria do Rosário Andrade Barreto Ferreira",
      "Naickely Monteiro Fernandes",
      "Pedro Henrique Nunes da Silva",
      "Pedro Lucas Angeli Silva",
      "Sara Bispo Menezes",
      "Alana dos Santos Moreira",
      "Giselle Dias Alves",
      "Weslley Marçal Neves",
    ],
  },
  {
    descricao: "Lista de Excedentes",
    pessoas: [
      "Adriano José Barbosa Matos",
      "Alana Maqueise Silva Cruz",
      "Alberty Silva Berto",
      "Alessandro Alcantara dos Santos",
      "Alex Olivreira Alves",
      "Alexa Souza dos Santos",
      "Alícia Báfica Silva",
      "Alina Santos de Souza Costa",
      "Aline de jesus Aquino Pereira",
      "Alysson Cardoso Costa",
      "Amanda Alves Xavier",
      "Amanda Santana Póvoas",
      "Amanda Souza Barros",
      "Ana Carla Pavani Silva",
      "Ana Caroline Neris Fonseca",
      "Ana Cecília Schiavinato Brito da Silva",
      "Ana Clara Duarte Barreto",
      "Ana Luiza Luna Miranda",
      "Ana Luiza Nunes Damião",
      "Ana Paula de Jesus Martins",
      "Anderson Gonçalves de Sousa",
      "Andrew Armando da Silva Castro",
      "Angie Jennifer Georget Garcia Dominguez",
      "Anna Regina Santos Vieira",
      "Arthur Cardoso dos Santos",
      "Artur Nicolas do Carmo de Souza",
      "Bárbara Júlia Góis Vivas de Souza",
      "Beatriz Fontes Souza",
      "Beatriz Mendonça Lins",
      "Beatriz Santos Seibert Dos Passos",
      "Bianca Amaral Salvador",
      "Bianca Araújo Dos Santos Nascimento",
      "Bianca Marques Vieira",
      "Bianca Ramielly Bonfim de Jesus",
      "Brida Karoline Santos Souza",
      "Bruno Simões de Oliveira dos Santos",
      "Caio Grako Ferreira da Silva",
      "Caio Rocha Matos",
      "Caio Souza Almeida",
      "Camille Santos Torres",
      "Carlos da Conceição Bomfim",
      "César Evaristo dos Santos",
      "Charles dos Santos Muniz",
      "Clara Aparecida Silva Bezerra",
      "Cláudia Reis Santos",
      "Crislane da Silva Santos",
      "Cristian Silva Gusmão",
      "Cristiano Jesus da Silva",
      "Cristina Maria da Silva",
      "Daniel Carlos Pereira de Oliveira",
      "Daniel Coutinho Silva",
      "Daniel Loureiro Magnavita da Silva",
      "Daniela Baldez Vidal Couto",
      "Daniele Santos de Sousa",
      "Darlysson Pereira Machado",
      "Davi Oliveira dos Santos",
      "Derlyn Johana Solano López",
      "Diego Ramos do Nascimento",
      "Edivaldo Alves de Jesus",
      "Edson da silva de França",
      "Elijersse dos Santos",
      "Elimardo Cavalcante Bandeira",
      "Elizeu Machado dos Santos",
      "Ellen Stefane Santos Luiz",
      "Elloysa Sales da Silva Aranha",
      "Emanoel dos Santos Santos",
      "Emanuele Pereira Oliveira",
      "Emanuelly França Oliveira",
      "Emilly Lago Silva",
      "Emily Kaís Souza de Oliveira Nepomuceno",
      "Erica Herminia da Silva Rosario",
      "Escarlett de Arruda Ramos",
      "Estefane Jordana Brandão Oliveira",
      "Ester da Cunha Meira Santos",
      "Ewerton Soares Martins",
      "Fabricio Ruan Costa Neri",
      "Felipe Andrade Carregosa",
      "Felipe Gregue Chaves Pires",
      "Flávio Rabelo de Morais Neto",
      "Gabriel Alves da Silva",
      "Gabriel Fernando Duarte de Bairros",
      "Gabriel Morais Miranda",
      "Gabriel Santos Almeida",
      "Gabrielle Rodrigues Soares",
      "Geni Alves Casteliano",
      "Geovana dos Santos",
      "Geovane Jesus dos Santos",
      "Geovânia Santos Souza",
      "Gilberto Bandeira dos Santos Filho",
      "Giselle Torres Borges Pereira",
      "Grecilane Santos Bomfim",
      "Guilherme Vieira Albuquerque",
      "Hellen Gabrielle Silva Rosa",
      "Henrique Fernando Santos da Silva",
      "Hortência Carvalho da Costa",
      "Iara Brito de Andrade",
      "Igor Ferreira da Silva",
      "Igor Régis do Nascimento",
      "Inara Luanda Viana Sousa",
      "Indyana dos Santos Santana",
      "Isabele Pereira de Sousa",
      "Isabelle da Silva Santos",
      "Isadora Ângela Luz Santos",
      "Isidro Adriano Mazuze",
      "Italo Enzo da Silva Gonçalves",
      "Iuri Carvalho Passos",
      "Jade Santos Brito",
      "Jádice Karaí Santos Costa Silva",
      "Jairon Gomes da Silveira Júnior",
      "Jean Lesly Charles",
      "Jeferson Goldman de Andrade",
      "Jeniffer de Barros Cabral",
      "Jessika Kauanny de Souza Eurico",
      "Joadson de Jesus Oliveira",
      "João Álefe Oliveira Guimarães",
      "João André Ramos Carilo Galvão",
      "João Vitor Alexandre Santos",
      "João Vitor Guimarães dos Santos",
      "João Vitor Silva Teles",
      "Jônatas de Sá Santos",
      "José Ricardo Santos",
      "José Tássio Vinicius dos Santos",
      "Juan Pablo Medina Vargas",
      "Júlio Silva Neves",
      "Jullyana Costa dos Santos",
      "Karla Cristiane Calazans Santos Viana",
      "Kauan Gama de Souza",
      "Kesya Ribeiro Domingas dos Santos",
      "Klaus Bispo de Assis",
      "Klaus Cardoso Oliveira Lima",
      "Kris Santos Veloso",
      "Laila Santana Gomes",
      "Lara Beatriz Correia Moreira de Vasconcelos",
      "Lara Souza Mendonça",
      "Laura Vitória Tolentino da Silva",
      "Leonardo Silveira Gomes",
      "Ligya Castro Santos",
      "Lílian Albino Nascimento",
      "Lizandra Santos Moura",
      "Lorena Andrade de Araújo",
      "Lorena Brito Pimentel Rodrigues dos Santos",
      "Lorena Mota Machado",
      "Lorraine Santos de Souza",
      "Luan Aguiar de Carvalho Oliveira",
      "Luana Santos Sales",
      "Luciano de Jesus Santos",
      "Luisa Santos Prates",
      "Luiz Augusto Vicente Barbosa",
      "Luiz Fillipe Silva Moreira",
      "Luiz Guilherme Bandeira Zanino",
      "Luíz Paulo Nascimento de Souza",
      "Luiza Silva Santos",
      "Maiara Alves Passos",
      "Manuela Ruiz Miranda",
      "Marcelle Leão de Brito",
      "Marcelo Bomfim da Silva",
      "Marcelo Jesus dos Santos",
      "Márcia Elias Seif",
      "Marco Antonio Santana Roque",
      "Marcos Vinicius Santos Nascimento",
      "Maria Clara Alves Pereira",
      "Maria Clara Barbosa da Silva",
      "Maria Clara Souza Passos",
      "Maria Eduarda Andrade Carneiro",
      "Maria Eduarda Lima Santos",
      "Maria Hellen Oliveira Andrade",
      "Maria Izabel Batista Pereira",
      "Maria Luiza Dos Santos Gratão",
      "Mariana dos Santos Silva",
      "Mariana Oliveira Figuêredo Peltier",
      "Marilu Neiva Lira",
      "Marina de Jesus Souza",
      "Marina Ribeiro da Silva",
      "Mateus Ruben Mussane",
      "Matheus Carvalho dos Santos",
      "Matheus Nascimento",
      "Matheus Silva Teles",
      "Mavione de Jesus Primo",
      "Maysa Gabrielly Santos Monteiro",
      "Miguel José Carneiro Neto",
      "Misael da Silva Santiago",
      "Mônica dos Santos Alves",
      "Myllena Souza da Silva",
      "Náira Vitória Nascimento Alves dos Santos",
      "Natany Moreno Teles",
      "Nathalia Santos da Silva",
      "Nelson Manoel Dos Santos Neto",
      "Nicolle Andrade Novais Pereira",
      "Otávio de Oliveira Moreira",
      "Palmira Lino dos Santos Neta",
      "Patricia Souza Nascimento Gama",
      "Paula Dilamar Cordier Gomes",
      "Paula Emily de Jesus Fagundes",
      "Paulo Willian Gouveia Andrade Junior",
      "Pedro Luiz Santos Gomes",
      "Quênia Neves Viana",
      "Rafaela Caldas Sousa dos Santos",
      "Rafaela Ferreira Borges",
      "Raquel Ferreira dos Santos",
      "Renata Berbert Rolim",
      "Renata Costa Lima",
      "Ricardo de Jesus Silva",
      "Rivana Lacerda Pires de Oliveira",
      "Ruan Rosetti da Silva",
      "Sabryna Couto Araujo",
      "Samuel Oliveira Dos Santos",
      "Samy Celes Barrozo",
      "Sandy Stely dos Santos Mercês",
      "Santielly Ramos de Oliveira",
      "Simone Alves dos Santos",
      "Sinara dos Santos Machado",
      "Stefanie Maria Pinto de Oliveira Silva",
      "Tainá Caldas de Jesus",
      "Tainara de Jesus Santos",
      "Thácyla Regina Martins Leite",
      "Thamirys Dias de Luna Paiva",
      "Thaty Milly da Silva Alexandrino",
      "Tiago Rocha Riso Lopes",
      "Túlio Santos Braz",
      "Vanessa de Jesus da Silva",
      "Vanessa Evangelista de Souza",
      "Vaniele Rocha Santos",
      "Vinicius de Jesus dos santos",
      "Wagner Ferreira da Silva",
      "Wanessa Machado de Araújo",
      "Wenndell Santos Sotero",
      "Wesley Francisco do Nascimento",
      "Yago Rodrigues Vieira",
      "Zaira dos Santos Velozo",
    ],
  },
];
