export const entrevistasArray = [
  {
    horario: "21 de agosto, às 9h30",
    pessoas: [
      "Breno Gonçalves Pirôpo",
      "João Victor Gondin Nascimento",
      "Gabriel Reis Ferreira",
      "Alana dos Santos Moreira",
      "João Victor Nunes Barra dos Santos",
      "Rosana Queiroz Santos Caldas",
      "Antoniel Neves Cruz",
      "Naickely Monteiro Fernandes",
      "Luana Maria Figueiredo Paes",
      "Lêda Maria Sousa Santos",
      "Zahir Sousa Cruz Matos Cardoso",
      "Pedro Henrique Nunes da Silva",
      "Andressa Galdino Pereira",
      "Heloísa Silva Menezes",
      "Ana Ilza Alves de Jesus Farias",
      "Maria Luiza Braga dos Reis",
      "Ana Clara Oliveira Ramos",
      "Éder Oliveira Lima",
      "Ricardo Lucas Novaes",
      "Andreia Andrade dos Santos",
    ],
  },
  {
    horario: "21 de agosto, às 14h",
    pessoas: [
      "Yasmin de Oliveira Barcellos",
      "Maria do Rosário Andrade Barreto Ferreira",
      "Elisangela Silva Bispo Lima",
      "Lucas Martins Almeida",
      "Bruno dos Santos Reis",
      "Giselle Dias Alves",
      "Nair Emanuelle Trindade",
      "Weslley Marçal Neves",
      "Ramon Santos Costa",
      "Claudia Helena Sierra Nova",
      "Adeilma Rodrigues da Silva",
    ],
  },
  {
    horario: "22 de agosto, às 9h30",
    pessoas: [
      "Claudio Marcelo Ribeiro Barbosa",
      "Elise Mendes Cardoso",
      "Fellipe Faria de Oliveira",
      "Sara Bispo Menezes",
      "Elias Andrade dos Santos de Oliveira",
      "Marcel Mascarenhas Andrade",
      "Sabrina Nanine Miqueline dos Santos",
      "Geovana Pires Lima",
      "Socrates Jacobo Moquete Guzmán",
      "Mayra Honorato Santos Araújo",
      "Saymon Stanley Silva de Oliveira",
      "Bianca Ramos Santos",
    ],
  },
  {
    horario: "22 de agosto, às 14h",
    pessoas: [
      "Carolayne Nascimento Rocha",
      "Brena Velozo Santana",
      "Viviane Augusta Carvalho Falcão",
      "Michel Felipe Lima de Araújo",
      "Brenda Reis Luz",
    ],
  },
  {
    horario: "23 de agosto, às 9h30",
    pessoas: [
      "Émerson Bernardi",
      "Hevellin Santos Cardoso",
      "Pedro Lucas Angeli Silva",
      "Júlia Angeli da Silva",
    ],
  },
  {
    horario: "23 de agosto, às 14h",
    pessoas: [
      "Jaciane Rodrigues dos Santos",
      "Sonia María Chacaliaza Cruz",
      "Diogo Ramos Cerqueira",
      "Diego Melo Cardoso social Samantha",
      "Alan Kleber Santos de Almeida",
    ],
  },
  {
    horario: "23 de agosto, às 18h",
    pessoas: [
      "Karla Cristiane Calazans Santos Viana",
      "Pedro Souza Santos Medeiros",
    ],
  },
];
