export const resultadoFinalArray = [
  {
    turma: "UE0A - Pré-iniciante - Terças e Sextas - 8h30 - 10h",
    pessoas: [
      "Amanda Gabrielly Santana Silva",
      "Anderson da Silva Oliveira",
      "Carina Aparecida Paraizo Silva",
      "Evelyn Francenet Neuta Chiguasuque",
      "Iago Cristian Gomes de Menezes",
      "Indaiá Menezes Lapa",
      "Jennyffer Andreina Reyes Polanco",
      "Jéssica Alana Souza da Silva",
      "João Miguel Loduvico Nascimento de Menezes",
      "Joara Barbosa Brito",
      "Kaique Ruan Batista",
      "Laisa Pena Freitas",
      "Leandra Sales da Silva",
      "Leiliane Quelen De Jesus Mendes",
      "Luiz Henrique Silva Conceição",
      "Luíza Delkarin Pereira Dias",
      "Mariana Ribeiro dos Santos",
      "Paloma Almeida de Santana",
      "Tamiles Costa Ribeiro",
      "Weverton Moreira dos Santos",
    ],
  },
  {
    turma: "UE0B - Pré-iniciante - Quartas - 14h30 - 16h30",
    pessoas: [
      "Bianca Lima dos Santos",
      "Breno Gonçalves Pirôpo",
      "Débora Sousa dos Santos",
      "Ediná Santos Rocha Campos",
      "Felipe dos Santos Dias",
      "Geovanna Alves Pereira",
      "Heleny Chaves da Silva Alves",
      "Isadora Pereira Gazzi Martins",
      "Isis Luiza de Lima Teixeira",
      "Jucimara Viana Neves",
      "Jucineide França Alcântara",
      "Luiz Henrique dos Santos Blume",
      "María Fernanda Tulcán Eraso",
      "Mayra Honorato Santos Araújo",
      "Naiara Almeida de Assis",
      "Nidia Ligeya Daza Hernández",
      "Rafaela Almeida da Silva",
      "Ramon Santos Costa",
      "Samuel dos Santos Oliveira",
      "Sócrates Amauri da Silva Guzmán",
      "Sunamita Damasio Vieira",
      "Valentina Paz Tobar Tobar",
    ],
  },
  {
    turma: "UE0C - Pré-iniciante - Quartas e Quintas - 16h30 - 18h",
    pessoas: [
      "Aline Vieira da Silva",
      "Ana Paula Silva Sousa Santos",
      "Carlos Vitorio de Oliveira",
      "Caroline Gonçalves Sousa",
      "Daniel Marcos Santos Marinho",
      "Durval de Jesus Santos",
      "Edma de Oliveira Santos",
      "José Vitor dos Santos Costa",
      "Josenilson Leitão da Silva",
      "Katielle Barbosa",
      "Marcus Edson Carilo de Mello Vieira",
      "Mariana Santos Lopes",
      "Milena de Oliveira Rebuli",
      "Nidia Ligeya Daza Hernández",
      "Rayssa Fernandes Felipe",
      "Rosana Queiroz Santos Caldas",
      "Samara Luiza Oliveira Nascimento",
      "Taciana Vargas Fabris",
      "Talita Oliveira de Souza",
      "Vera Lúcia Macêdo Sousa Lapa",
      "Wagner de Oliveira Rodrigues",
    ],
  },
  {
    turma: "UE1A - Iniciante - Terças e Quintas - 13h30 - 15h",
    pessoas: [
      "Adriana Josefa da Rocha",
      "Brena Velozo Santana",
      "Camila Santos da Silva",
      "Catarine Santos Santana",
      "Claudia Helena Sierra Nova",
      "Claudio Marcelo Ribeiro Barbosa",
      "Danielle Costa Suares",
      "Jaciane Rodrigues dos Santos",
      "Jemima Santos Galdino",
      "Júlia Santos Virolli Chaves",
      "Kailanne Silva dos Santos",
      "Lavinia Brasilino de Moraes",
      "Letícia Calhau Sampaio",
      "Maria Alejandra Rivillas Carmona",
      "Maria Etiele Novais Mota",
      "Mariana Macêdo e Souza",
      "Patricia dos Santos Gonçalves Sousa",
      "Saymon Stanley Silva de Oliveira",
      "Socrates Jacobo Moquete Guzmán",
      "Sonia María Chacaliaza Cruz",
      "Tatiane Reis da Silva",
      "Yasmin de Oliveira Barcellos",
      "Yasmine Gonçalves dos Santos Conceição",
    ],
  },
  {
    turma: "UE2A - Pré-intermediário - Terças e Quintas - 15h - 16h30",
    pessoas: [
      "Alessandra Oliveira dos Santos",
      "Alexandre Pedreira da Paixão",
      "Ana Catharina Oliveira Santos",
      "Brenda Reis Luz",
      "Elias Andrade dos Santos de Oliveira",
      "Emanuelle Silva Fonseca",
      "Fabrício Alcântara Barbosa Silva",
      "Israel Santana dos Anjos",
      "João Victor Gondin Nascimento",
      "Laércio dos Santos",
      "Luy Rocha Loyola de Andrade",
      "Marcel Mascarenhas Andrade",
      "Michel Felipe Lima de Araújo",
      "Oswaldo Dias dos Santos Filho",
      "Thamiles Lessa dos Santos",
    ],
  },
  {
    turma: "UE3A - Intermediário básico - Terças e Sextas - 10h - 11h30",
    pessoas: [
      "Bruno dos Santos Reis",
      "Éder Oliveira Lima",
      "Elisangela Silva Bispo Lima",
      "Elise Mendes Cardoso",
      "Émerson Bernardi",
      "Fellipe Faria de Oliveira",
      "Heverton Soares dos Santos Oliveira",
      "Júlia Angeli da Silva",
      "Lêda Maria Sousa Santos",
      "Lucas Martins Almeida",
      "Mariângela Oliveira Gomes Valeriano",
      "Nair Emanuelle Trindade",
      "Pedro Souza Santos Medeiros",
      "Viviane Augusta Carvalho Falcão",
      "Zahir Sousa Cruz Matos Cardoso",
    ],
  },
  {
    turma: "UE4A - Intermediário - Quartas - 09h30 - 11h30",
    pessoas: [
      "Ana Clara Oliveira Ramos",
      "Ana Ilza Alves de Jesus Farias",
      "Andreia Andrade dos Santos",
      "Andressa Galdino Pereira",
      "Antoniel Neves Cruz",
      "Bianca Ramos Santos",
      "Bruno Anuar Webi",
      "Camilly Mel Barbosa dos Santos",
      "Éricka Luanny Machado Maia",
      "Gabrielle Souza de Paula",
      "Geovana Pires Lima",
      "Heloísa Silva Menezes",
      "João Victor Nunes Barra dos Santos",
      "Maria Luiza Braga dos Reis",
      "Ricardo Lucas Novaes",
      "Sabrina Nanine Miqueline dos Santos",
    ],
  },
];
