export const ausentesExcedentesArray = [
  {
    descricao: "Lista de Excedentes",
    pessoas: [
      "Addriel Soares Moreira",
      "Alice Oliveira Reis",
      "Ana Clara Simões da Silva",
      "Anderson da Silva Oliveira",
      "André Luiz de Alcântara Brandão",
      "Antonio Iderval Sodré Neto",
      "Bruno Anuar Webi",
      "Bruno dos Santos Reis",
      "Caio Grako Ferreira da Silva",
      "Caroline santos Almeida",
      "Cristian Silva Gusmão",
      "Derlyn Johana Solano López",
      "Diego Ramos do Nascimento",
      "Fernanda Sousa dos Santos",
      "Flávio Rabelo de Morais Neto",
      "Gisele Motta Ferreira",
      "Henrique Daniel Resende",
      "Hermano Cardoso de Andrade",
      "Ian Robert Luz Pinheiro",
      "Jessika Kauanny de Souza Eurico",
      "João Gabriel Nascimento Weyll",
      "João Pedro Pinto Assis",
      "José Luiz Jesus Santana",
      "Laila Santana Gomes",
      "Lara Perelo Lavinscsky",
      "Laura Scaldaferri",
      "Leonardo Santos Lemos",
      "Lorena Alves Moreira",
      "Lueny de Souza Rodrigues",
      "Maria Cecília Galvão Sá",
      "Maria Eduarda Andrade Carneiro",
      "Mariana Cecilia de Carvalho",
      "Michelle Alejandra Estévez Haro",
      "Naickely Monteiro Fernandes",
      "Náira Vitória Nascimento Alves dos Santos",
      "Pedro Souza Santos Medeiros",
      "Raquel Ferreira dos Santos",
      "Saray Carolina Carrillo Paternina",
      "Tarcísio Miguel dos Santos Magalhães",
      "Vitor Hugo Yukio Fugivala",
      "Vitória Cristina Ferreira Oliveira",
      "Zilma dos Santos Félix Vasconcelos",
    ],
  },
];
